version: 2
updates:
  - package-ecosystem: npm
    directories:
      - /
      - /packages/*
      - /examples/*
      - /e2e
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      better-auth:
        patterns:
          - "better-auth"
          - "@better-auth/*"
      patch-only:
        update-types:
          - patch
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-major"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-major"
